version: '3.8'  # Указываем версию Compose

services:  # Секция сервисов
  nginx:
    image: nginx:stable-alpine
    ports:
      - "9080:80"
      - "9443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "/etc/letsencrypt:/etc/letsencrypt"
    depends_on:
      # - backend
      - frontend
    networks:
      - dev

  frontend:
    image: ivanknyazev/t1-hack-frontend:0.2
    #build:
    #  context: ./t1_help_bot
    networks:
      - dev

networks:  # Секция сетей
  dev:
