version: '3.8'  # Указываем версию Compose

services:  # Секция сервисов
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "/etc/letsencrypt:/etc/letsencrypt"
    depends_on:
      # - backend
      - frontend
    networks:
      - dev

  frontend:
    build:
      context: ./t1_help_bot
    networks:
      - dev

networks:  # Секция сетей
  dev:
