networks:
  dev:
  services:
    nginx:
      image: nginx:stable-alpine
      ports:
        - "8080:80"
        - "8443:443"
      volumes:
        - "./nginx.conf:/etc/nginx/nginx.conf"
        - "/etc/letsencrypt:/etc/letsencrypt"
      depends_on:
      # - backend
        - frontend
      networks:
        - dev
    frontend:
      build:
        context: ./frontend
      networks:
        - dev
        
