name: 'service-freeline'

volumes:
  postgres-data:


networks:
  postgres-network:
    driver: bridge

services:
  postgres:
    container_name: postgres-freeline
    image: 'postgres:15'
    env_file:
      - .env
    environment:
      TZ: 'GMT+3'
      PGTZ: 'GMT+3'
    restart: unless-stopped
    volumes:
      - database/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres-network

  backend:
    container_name: backend-freeline
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - "POSTGRES_HOST=postgres"
      - "TZ=Europe/Moscow"
    #    command: "uvicorn backend.main:app --port ${BACKEND_PORT} --host 0.0.0.0"
    ports:
      - 8000:8000
    networks:
      - postgres-network
